server:
  port : 9090
  
spring:
  datasource:
     type: com.zaxxer.hikari.HikariDataSource
     jdbcUrl: ENC(nn10FOsrA8SzV+ttde+3ziIRtokhVRQIjSmS8jCT+8omm0tuKoPF7bERIxww4pAudu/bEYPDSM4=)
     username: ENC(9dhe9+K+ykijQiYE9O5NsQ==)
     password: ENC(h6u2uZ0Y71nC6Do6goDabnxshB/GazSTx11d3RzotQI=)